name: "World-Dropup"
main: tw.mayortw.dropup.DropupPlugin
version: 0.2
description: "Back up worlds to Dropbox"
author: "R26"
softdepend:
    - Multiverse-Core
commands:
    dropup:
        usage: |
            Commands:
                backup [world]
                restore <world> <backup>
                uploadspeed [speed]
                downloadspeed [speed]
                disable [reason]
                enable
                list [world] [max display]
                book
                signin [code]
        aliases: ["du"]
        permissions: dropup.*
permissions:
    dropup.disable:
        default: op
    dropup.backup:
        default: op
    dropup.restore:
        default: op
    dropup.signin:
        default: op
