name: "World-Dropup"
main: tw.mayortw.dropup.DropupPlugin
version: 0.3.4
description: "Back up worlds to Dropbox"
author: "R26"
api-version: 1.13
softdepend:
    - Multiverse-Core
    - WorldEdit
commands:
    dropup:
        usage: |
            Commands:
                backup | bk [world]
                backupall | bkall
                backuptime | bktime [time]
                restore | re <world> <backup>
                uploadspeed | us [speed]
                downloadspeed | ds [speed]
                disable [reason]
                enable
                list | ls [world] [max display]
                status | st
                menu | me
                signin [code]
        aliases: ["du"]
permissions:
    dropup.disable:
        default: op
    dropup.backup:
        default: op
    dropup.restore:
        default: op
        children:
            dropup.list: true
    dropup.list:
        default: op
    dropup.setting:
        default: op
    dropup.signin:
        default: op
    dropup.*:
        default: op
        children:
            dropup.disable: true
            dropup.backup: true
            dropup.restore: true
            dropup.list: true
            dropup.setting: true
            dropup.signin: true
