name: "World-Dropup"
main: tw.mayortw.dropup.DropupPlugin
version: 0.5.3
description: "Back up worlds to Dropbox"
author: "R26"
api-version: 1.13
softdepend:
    - Multiverse-Core
    - WorldEdit
commands:
    dropup:
        usage: |
            Commands:
                backup | bk [world] 備份只定的世界
                backupall | bkall 備份所有世界
                backuptime | bktime [time] 設定自動備份的最短間隔
                maxbackup | maxbk [max] 設定最大備份數量
                restore | re <world> <backup> 恢復世界到之前的備份
                delete <world> <backup> 刪除備份
                uploadspeed | us [speed] 限制上傳速度。設成 -1 等於無限制
                downloadspeed | ds [speed] 限制下載速度。設成 -1 等於無限制
                disable [reason] 暫時停用自動備份
                enable 重新啟用自動備份
                reload | rl 重載設定檔
                list | ls [world] [max display] 世界和備份列表
                status | st 備份狀態
                menu | me 備份選單
                signin [code] 登入 Dropbox
        aliases: ["du"]
permissions:
    dropup.disable:
        default: op
    dropup.backup:
        default: op
    dropup.restore:
        default: op
        children:
            dropup.list: true
    dropup.delete:
        default: false
        children:
            dropup.list: true
    dropup.list:
        default: op
    dropup.setting:
        default: op
    dropup.signin:
        default: op
    dropup.*:
        default: op
        children:
            dropup.disable: true
            dropup.backup: true
            dropup.restore: true
            dropup.list: true
            dropup.setting: true
            dropup.signin: true
