name: "World-Dropup"
main: tw.mayortw.dropup.DropupPlugin
version: 0.2
description: "Back up worlds to Dropbox"
author: "R26"
softdepend:
    - Multiverse-Core
    - WorldEdit
commands:
    dropup:
        usage: |
            Commands:
                backup|bk [world]
                restore|re <world> <backup>
                uploadspeed|us [speed]
                downloadspeed|ds [speed]
                disable [reason]
                enable
                list|ls [world] [max display]
                menu|me
                signin [code]
        aliases: ["du"]
        permissions: dropup.use
permissions:
    dropup.use:
        default: op
    dropup.disable:
        default: op
    dropup.backup:
        default: op
    dropup.restore:
        default: op
    dropup.list:
        default: op
    dropup.signin:
        default: op
